### ISSUE TITLE
Some inquires

### ISSUE THREAD

**Issue by eriksvedang** [harlanhaskins/LLVMSwift#43]
Hello! Sorry if this is the wrong place for this kind of questions, I didn't know where to put them. I could write an email I guess but then no one else will be able to read the response, which seems inefficient :)

1. I'm shopping around for LLVM bindings and so far these ones are the nicest (by far!). Without actually trying to implement my idea for a programming language it's hard to judge how complete they are, though. Are there any big parts missing that I should know about?

2. It seems like Apple should provide "official" Swift bindings given their big investment in the language, is there a plan for making these bindings part of the official LLVM distribution or something similar? (similar to the Ocaml bindings that are in there now)

Cheers, and big thanks for creating this nice project!

Erik

**Comment by harlanhaskins** [comment]
Hi Erik! We don't have a mailing list or a Slack, so I think this is the best way to reach us for now.

Thanks for your interest in this project! We're very excited to get it out there and we hope people make some amazing things with it!

To answer your questions:

1) We're not completely covering the LLVM C API quite yet. However, if there is something that's incomplete that we haven't gotten around to adding yet, and you need it, it's actually pretty simple to make API bindings. We'd absolutely love contributions!
Of the things listed in the [LLVM C API documentation](http://llvm.org/docs/doxygen/html/group__LLVMC.html), we have implemented most of the `Core` and `Target information` modules, and some of the `Execution Engine` modules. These are by far the most common things you'll need for a compiler.
The most glaring thing that's missing from the C API, in my experience, is anything relating to debug information generation. We hope to tackle this and maybe push a patch back to LLVM, though that's far in the future.

2) Unfortunately, I don't think Apple will be providing official Swift bindings because the Swift compiler is written in C++ and will stay that way for the foreseeable future. We currently don't have a plan to integrate these into the "Official" LLVM distribution, though we would welcome discussions!

Thanks again for your enthusiasm!

Harlan

**Comment by eriksvedang** [comment]
Awesome, thanks for the quick reply. I will gladly make contributions if there is something I find is missing and I can figure out how to add it. I think I'll go ahead and work a bit on my language and see what comes up.

**Comment by harlanhaskins** [comment]
Awesome! If you ever want to contribute, we'll be more than happy to help out.

You should have everything you need for a simple language already -- for example, [Trill](https://github.com/trill-lang/trill) uses LLVMSwift for its codegen already!

**Comment by harlanhaskins** [comment]
We actually now have a slack that you can join here: https://llvmswift-slack.herokuapp.com
